# Generated by Django 5.2 on 2026-05-04 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Habitacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=10, unique=True)),
                ('tipo', models.CharField(choices=[('individual', 'Individual'), ('doble', 'Doble'), ('suite', 'Suite')], max_length=20)),
                ('capacidad', models.IntegerField()),
                ('precio_por_noche', models.DecimalField(decimal_places=0, max_digits=10)),
                ('descripcion', models.TextField(blank=True)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='habitaciones/')),
                ('disponible', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Habitación',
                'verbose_name_plural': 'Habitaciones',
            },
        ),
    ]
